#!/bin/bash

REPO_OPTIONS="--setopt=updates-modular.module_hotfixes=true --setopt=fedora-modular.module_hotfixes=true"

cat /etc/fedora-release | grep "Rawhide"
if [ $? -eq 0 ]; then
    REPO_OPTIONS="--setopt=rawhide-modular.module_hotfixes=true"
fi

for i in $(dnf $REPO_OPTIONS repoquery $*); do
    echo "$i $(dnf $REPO_OPTIONS module provides $i | grep "^Module" | sed 's/^Module *: *\(.*:.*\).*$/(\1)/' | sort -u | xargs)"
done
